# Generated by Django 6.1 on 2026-08-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://www.runawayapricot.com/wp-content/uploads/2014/09/placeholder.jpg', max_length=500),
        ),
    ]
