# Generated by Django 6.1 on 2026-08-27 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_item_base_item_item_na_6f24ae_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
